### ISSUE TITLE
Generation of positions.txt

### ISSUE THREAD

**Issue by alyosama** [jianhuupenn/SpaGCN#10]
Hello

I have a visium data that was processed using spaceranger but I didn't find the positions.txt file in the output directory. 
However, I tried to generate it using scanpy in adata.obs where I can find the position of every spot but I can't map it to pixels in unstructured data in the object (adata.uns) 

So How did you generate the positions file as I found it is mandatory to run SpaGCN on it ?

Thanks,

**Comment by jianhuupenn** [comment]
Hi Alyosama,
Thanks for your interest in SpaGCN.
I am not familiar with raw Visium data processing, and cannot provide any suggestions on how to get the position file using spaceranger.
I am not very clear about your question, but if you have coordinated but not matched the histology image, you can either
1. Do mapping manually to get x_pixel and y_pixel
or
2. Use x_array, y_array instead of x_pixel and y_pixel, and run SpaGCN without histology image. In tutorial section 4,  
```
#If histlogy image is not available, SoaGCN can calculate the adjacent matrix using the fnction below
#adj=calculate_adj_matrix(x=x_pixel,y=y_pixel, histology=False)
```

**Comment by jianhuupenn** [comment]
Sorry, I have not generated any positions.txt myself. I directly use the "tissue_position_list.csv" file from 10X to get the array and pixel coordinates.
