### ISSUE TITLE
Integrating consecutive slides

### ISSUE THREAD

**Issue by tpentim** [jianhuupenn/SpaGCN#14]
Hi Jian,
thanks for releasing this very nice tool! I was wondering: what would be the best way to integrate consecutive slides (like you show for the two posterior mouse brain sections in the paper)? 

Best,
Tancredi

**Comment by jianhuupenn** [comment]
Hi Tancredi,

Thanks for raising this great question. 
For slides that are adjacent and on the same plane, you can refer to tutorial section 8.
For slides that are continuously cut from the same section(e.g, 2 posterior slides from the same tissue), you can either:
1. Run SpaGCN on each separately, which should result in similar spatial domains. Then you can map them together by location and SVGs.
or
2. Run the multi-section version SpaGCN. I haven't got a chance to add that part into the tutorial because usually step 1 can already generate very clear results. Here is some sample code in case you want to use it:
```
#Section 1
adata1.var_names_make_unique()
adata1.raw=adata1
sc.pp.normalize_per_cell(adata1, min_counts=0)
sc.pp.log1p(adata1)
#Section 2, you can add more sections
adata2.var_names_make_unique()
adata2.raw=adata2
sc.pp.normalize_per_cell(adata2, min_counts=0)
sc.pp.log1p(adata2)

p=0.5 
l1=spg.search_l(p, adj1, start=0.01, end=1000, tol=0.01, max_run=100)
l2=spg.search_l(p, adj2, start=0.01, end=1000, tol=0.01, max_run=100)

r_seed=t_seed=n_seed=100
l_list=[l1, l2]
res=0.6
adata_list=[adata1, adata2]
adj_list=[adj1, adj2]
#Multi-section SpaGCN
clf=spg.multiSpaGCN()
clf.train(adata_list,adj_list,l_list,init_spa=True,init="louvain",res=res, tol=5e-3, lr=0.05, max_epochs=200)
```

**Comment by tpentim** [comment]
Thanks a lot for the code! I agree with you, results should be easily comparable between two consecutive sections. I just would like to improve the detection of rare clusters by doubling the number of spots :)
Best,
Tancredi

**Comment by Jylab-Genetics** [comment]
I have many periods, each with many consecutive slices. How should I do this
