### ISSUE TITLE
Unkown number of domains

### ISSUE THREAD

**Issue by ViriatoII** [jianhuupenn/SpaGCN#22]
Hi,

The tutorial and paper make it seem like SpaGCN can guess an optimal resolution without knowing the real number of domains in a dataset. 

> If the number of domains in the tissue is known ( ...). Otherwise, we vary the resolution parameter from 0.2 to 1.0 and select the resolution that gives the highest Silhouette score

So, running clf.train without the res parameter looks like this:

`
clf.train(adata,adj,init_spa=True,init="louvain", tol=5e-3, lr=0.05, max_epochs=200)`

```
Initializing cluster centers with louvain, resolution =  0.4
Epoch  0
Epoch  10
Epoch  20
delta_label  0.00487028191439543 < tol  0.005
Reach tolerance threshold. Stopping training.
Total epoch: 25
```

Is the output of this function corresponding to my quote of the paper? It seems to only try a single resolution (0.4) and does not seem to compare Silhouette scores.

Kind regards,
Ricardo

**Comment by jianhuupenn** [comment]
SpaGCN uses Louvain's clustering for initialization, which takes a resolution to determine the number of clusters as I explained here #5.
If you know the number of clusters, there is a step in the tutorial to search for a suitable resolution to achieve the number of clusters. SpaGCN itself does not contain the Silhouette scores calculation since it is only used for method evaluation. For real data analysis purposes, you can either set the number of clusters as the tutorial did or just try a few resolutions and pick the one you like.  I would recommend trying 0.2, 0.4, 0.6. Generally speaking, a higher resolution will result in more domains.

**Comment by ViriatoII** [comment]
Thank you, keep up the great work!
