### ISSUE TITLE
The problem of different results on DLPFC151673 data

### ISSUE THREAD

**Issue by DerekBin** [jianhuupenn/SpaGCN#34]
I did spatial clustering on DLPFC151673 according to the tutorial you provided, my results are slightly deviated from the results of your paper, in my training results, ARI=0.3928, while in yours, ARI=0.419. In addition, the spatial domain gap of visualization is a bit large. For data, the results I got during my data processing are consistent with your tutorial. For the running environment, my python version is 3.8.5, SpaGCN==1.2.2. I'm wondering what might be causing the biased results?

**Comment by reneezhang1011** [comment]
I have the same issue, my clutering results are different visually. I could send out my result and adj matrix.

**Comment by jianhuupenn** [comment]
Hi there,
Thanks for your interest in SpaGCN. Regarding your question, I think the difference is due to the difference in SpaGCN's versions. 
The results shown in the tutorial were obtained using an old version, in which the parameter "l" and "res" are searched manually to achieve the wanted "p" and number of clusters.
In the current version, to make the software more user-friendly, I added two new functions, "spg.search_l()" and "spg.search_res()" to automatically determined these parameters.  This may be the reason that the results are different. One example, when you are searching for resolution with n_clusters=5,  res=0.2 or 0.3 will both result in 5 clusters, but with different patterns. 

I'll update these two functions to make them more stable.

**Comment by reneezhang1011** [comment]
Hi Jian,
Thank you for your reply. Look forward to your updata. Is it possible for you to share the I and res for the tutorial, and we can check if we implement it in the right way? I am currently working on some downstream analysis, and your method will be very helpful.

**Comment by xiao-kong-long** [comment]
Hello, maybe I have found the reason, as the following picture:
![image](https://user-images.githubusercontent.com/53474978/217704701-31ee4ab2-1f85-4a0c-89c8-c9fe04c2b751.png)
Transforming the above to below, the ARI of DLPFC 151673 would be 0.5, which is consistent to paper reported.

**Comment by leader402** [comment]
> Hello, maybe I have found the reason, as the following picture: ![image](https://user-images.githubusercontent.com/53474978/217704701-31ee4ab2-1f85-4a0c-89c8-c9fe04c2b751.png) Transforming the above to below, the ARI of DLPFC 151673 would be 0.5, which is consistent to paper reported.

hi ， i try to change the code you mentioned ，but there was no change in the results , Do you have any other suggestions about this？

**Comment by xiao-kong-long** [comment]
> > Hello, maybe I have found the reason, as the following picture: ![image](https://user-images.githubusercontent.com/53474978/217704701-31ee4ab2-1f85-4a0c-89c8-c9fe04c2b751.png) Transforming the above to below, the ARI of DLPFC 151673 would be 0.5, which is consistent to paper reported.
> 
> hi ， i try to change the code you mentioned ，but there was no change in the results , Do you have any other suggestions about this？

No changes in results shows that you may not use adj as Adjancy Matrix or not use image information (use_image=False).

**Comment by alavarosoler** [comment]
After adjusting the code, I abandoned the recommended resolution value and tried multiple resolutions myself, achieving an approximate result with an ARI of 0.51. If reproduction is not successful, you might consider fluctuating around the recommended resolution to try different resolutions and thus obtain the result.
