### ISSUE TITLE
Reproduction issue on tutorial: error at the steps with louvain algorithm

### ISSUE THREAD

**Issue by huimin230** [jianhuupenn/SpaGCN#45]
Hi Dr. Hu,

I want to reproduce results via SpaGCN in the given tutorial (https://github.com/jianhuupenn/SpaGCN/blob/master/tutorial/tutorial.ipynb). However, I got error “BaseException: Could not construct partition: vector” which seems in the steps using Louvain algorithm.

Can you please provide any help to solve this problem?

Thanks,

**Comment by jianhuupenn** [comment]
Thanks for your interest in SpaGCN. If you are running on the toy data and got this error, I believe it is because of the support package versions. Could you check the package version, especially for louvain and scanpy?
A list of tested environments can be found here:
https://github.com/jianhuupenn/SpaGCN#versions-the-software-has-been-tested-on

**Comment by huimin230** [comment]
Hi Dr.Hu,

Thanks for your reply. I checked all packages version as below, the error still exists. BTW: my computer system is macOS Monterey Apple M1 Pro

System: Anaconda
Python: 3.10.4
Python packages: pandas = 1.5.0, numpy = 1.23.3, python-igraph=0.10.1, torch=1.12.1, louvain=0.7.1, scipy = 1.9.2, scanpy = 1.9.1, anndata = 0.8.0, natsort = 8.2.0, scikit-learn = 1.1.2
