### ISSUE TITLE
Is it possible to use SpaGCN to integrate several datasets (slides)?

### ISSUE THREAD

**Issue by Guangshuai-Jia** [jianhuupenn/SpaGCN#6]
Hi, 

SpaGCN  is a great work! 

I was wondering is it possible to use SpaGCN to integrate data from several samples?

I have 4 (A, B, C, D) slides from 4 different patients, and when I used Seurat to analyze it I found there is so strong batch effects that I could not use CCA to integrate them. 

I want to know, is there a way to use SpaGCN to identify modules in each slides, and then compare these modules (meta gene for each domain?) to identify shared and differential modules/domain among all samples.

Thank you for your time!

Best,
Guangshuai

**Comment by jianhuupenn** [comment]
Hi Guangshuai,

Thanks for your interest in SpaGCN. 
Yes, I think you can perform spatial domain detection within each slice and find Spatially Variable Genes for each domain. Next, you can identify the shared domains across different slices by looking at the overlapped SVGs. 

I suggest you lower the SVG detection criteria so that more SVGs will be detected, and you can find more overlapped SVGs across slices to find the shared domains. For example, in tutorial section 6. Identify SVGs:
```
min_in_group_fraction=0.8 #(can be changed to 0.5 or lower)
min_in_out_group_ratio=1  #(can be changed to 0.5 or lower)
min_fold_change=1.5 #(can be changed to 1.2 or lower)
```
Hope this helps,
Jian

**Comment by tpentim** [comment]
Hi Jian,
thanks for releasing this very nice tool! Following up on this issue, I was wondering: what would be the best way to integrate consecutive slides (like you show for the two posterior mouse brain sections in the paper)?
Best,
Tancredi
